# %player_level% -> return player level
# %mob_level% -> return mob level
# %mob_xp% -> return mob xp
# Placeholder with PlaceholderAPI support
# Summation: "number1 + number 2" ; Ex: "1 + 2" ➙ 3
# Subtraction: "number1 + number2" ; Ex: "5 - 3" ➙ 2
# Multiplication: "number1 * number2" ; Ex: "3 * 2" ➙ 6
# Division: "number 1 / number 2" ; Ex: "10 / 2" ➙ 5
# Division Remainder: "number1 % number2" ; Ex: "7 % 2" ➙ 1
# Exponential: "number^exponent" ; Ex: "2^3" ➙ 8
# Square Root: "@{number}" ; Ex: "@{16}" ➙ 4
# Percent: "percent # number" ; Ex: 10 # 20 (10% of 20) ➙ 2
DEBUG: false
USE_MANY_FILE: false
#true -> Use MMOXPAddon/Mobs/mobname.yml
#false -> Use mobs.yml
MOBS: #List mob, if you don't list here, mob won't give xp
  - EXAMPLE