MESSAGE:
  LEVEL_SO_HIGH: "&cYou need level lower &a%level%&c to make damage to mob %mob%"
  LEVEL_SO_LOW: "&cYou need Level higher &a%level%&c to make damage to mob %mob%"
XP-MIN: 0
# %player_level% -> return player level
# %mob_level% -> return mob level
# %mob_xp% -> return mob xp
# Summation: "number1 + number 2" ; Ex: "1 + 2" ➙ 3
# Subtraction: "number1 + number2" ; Ex: "5 - 3" ➙ 2
# Multiplication: "number1 * number2" ; Ex: "3 * 2" ➙ 6
# Division: "number 1 / number 2" ; Ex: "10 / 2" ➙ 5
# Division Remainder: "number1 % number2" ; Ex: "7 % 2" ➙ 1
# Exponential: "number^exponent" ; Ex: "2^3" ➙ 8
# Square Root: "@{number}" ; Ex: "@{16}" ➙ 4
FORMULA: "%mob_level% / %mob_level% * 2" #formula for give less xp when kill mobs out of level range
MOBS:
  EXAMPLEMOB:
    XP: 5
    LEVEL:
      MAX: 5
      MIN: 1