MESSAGE:
  LEVEL_SO_HIGH: "&cYou need level lower &a%level%&c to make damage to mob %mob%"
  LEVEL_SO_LOW: "&cYou need Level higher &a%level%&c to make damage to mob %mob%"
XP-MIN: 0
MOBS:
  EXAMPLEMOB:
    XP: 5
    LEVEL:
      MAX: 5
      MIN: 1