name: MMOXPAddon
version: '${project.version}'
main: net.danh.mmoxpaddon.MMOXPAddon
api-version: 1.13
authors: [ VoChiDanh ]
depend: [ MythicMobs, MMOCore, MythicLib ]
commands:
  mmoxpaddon:
    description: Main command